// SPDX-License-Identifier: Apache-2.0

/**
 * The demo's entry point: the application, on the root route.
 *
 * `/lab`, T4.6's fixture route, lived here until T8.3 retired it; every claim it carried is
 * mapped or retired in `specs/plans/t8-3-lab-retirement.md`.
 */

import { StrictMode, createElement } from "react";
import { createRoot } from "react-dom/client";

import "maplibre-gl/dist/maplibre-gl.css";

// MapLibre 6 resolves its worker relative to the *importing* chunk, so under a bundler that
// rewrites imports the request lands beside the rewritten chunk and 404s. Nothing errors: the
// map constructs, the style parses, sources emit `sourcedata`, and no tile is ever built. A
// canvas mounts and stays empty — which is precisely what a smoke test reporting "one canvas,
// no page errors" cannot tell apart from a working map.
//
// `?worker&url` asks the bundler for a URL it will actually serve. This is a **consumer**
// responsibility, documented as one: the engine cannot do it, because the right URL depends on
// the consumer's bundler. `maplibre-gl` is a peer dependency of `@mapatlas/maplibre` for the
// same reason, so the demo declares it directly.
import maplibreWorkerUrl from "maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url";
import { setWorkerUrl } from "maplibre-gl";

import { createApp } from "./app/app.js";

setWorkerUrl(maplibreWorkerUrl);

const app = document.querySelector<HTMLElement>("#app");
if (app === null) throw new Error("the demo page has no #app element to mount into");

// **The app** (T7.1 increment 1). It takes the root route and absorbs T6.2's persistence
// control and installation guidance, which are its own settings.
//
// The stylesheet hook stays on `body`: the page padding and reading width live on `body` and
// `#app`, and the route marker is what scopes them. It dates from when `index.html` was shared
// with a full-bleed fixture route; marking the route keeps the scope a fact of the DOM rather
// than a promise about selectors.
document.body.dataset["route"] = "root";

/**
 * The application shell's service worker (T7.1 increment 5c).
 *
 * Registered for the application only; the worker answers navigations to the root and leaves
 * every other path to the network.
 *
 * **Production only**, because `sw.js` is generated by `scripts/generate-service-worker.mjs`
 * from the emitted bundle and does not exist under the dev server — registering there would
 * fetch a 404 and fail, on every load, for nothing.
 *
 * A failed registration is reported and not thrown: the application works without it, and the
 * offline scenario asserts the worker took control rather than trusting this call to have
 * succeeded.
 */
if (import.meta.env.PROD && "serviceWorker" in navigator) {
  navigator.serviceWorker.register("/sw.js").catch((error: unknown) => {
    document.body.dataset["shellWorker"] = "failed";
    console.error("the app shell's service worker did not register", error);
  });
}

// `StrictMode` deliberately: React 19 double-invokes effects in development, and every React
// lifecycle bug this repo has hit — the composer's re-armed `live` ref, a panel appending
// twice — is one that only a second mount reveals. A demo that hid them would teach the wrong
// thing.
createRoot(app).render(createElement(StrictMode, null, createApp(new URL(window.location.href))));
